services:
  redis:
    image: redis:8.2.2
    restart: always
    command: ['redis-server', '--requirepass', 'intersec2026jayarutkid']
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./.data/redis:/data
  postgres:
    image: postgres:18.0
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - POSTGRES_PASSWORD=intersec2026jayarutkid
      - POSTGRES_USER=rctf
      - POSTGRES_DB=rctf
    volumes:
      - postgres-dev:/var/lib/postgresql/

volumes:
  postgres-dev:
