events {}

http {
    server {
        listen 80;
        server_name _;

        # Traefik is a bit annoying as it does not let us serve specific paths as fallback, and instead we need to
        # make nginx count everything as a 404 (while supporting returning the 503 response as well)
        location = /.rctf-operator/health {
            access_log off;
            return 200 'ok';
        }

        location = /.rctf-operator/404.html {
            alias /usr/share/nginx/error-pages/404.html;
        }

        location = /.rctf-operator/502.html {
            alias /usr/share/nginx/error-pages/502.html;
        }

        location / {
            return 404;
        }

        error_page 404 /.rctf-operator/404.html;
    }
}