blank_issues_enabled: false
contact_links:
  - name: Questions and support
    url: https://github.com/otter-sec/rctf/discussions
    about: Ask for help with running or configuring rCTF.
  - name: Documentation
    url: https://rctf.osec.io
    about: How to install rCTF and run an event.
