import { cp } from 'fs/promises'
import { join } from 'path'
import { brotliCompressSync } from 'zlib'

export type Backend = 'cloudflare-pages' | 'github-pages'

export async function copyWebBuild(
  webBuildDir: string,
  outputDir: string
): Promise<void> {
  await cp(webBuildDir, outputDir, { recursive: true })
}

export async function injectInterceptor(
  outputDir: string,
  interceptorScript: string,
  backend: Backend
): Promise<void> {
  const indexPath = join(outputDir, 'index.html')
  let html = await Bun.file(indexPath).text()

  html = html.replace(
    /(<head[^>]*>)/,
    `$1<script>${interceptorScript}</script>`
  )
  html = html.replace(
    /<meta\s+http-equiv=["']Content-Security-Policy["'][^>]*>/is,
    ''
  )

  await Bun.write(indexPath, html)
  await Bun.write(join(outputDir, '404.html'), html)
  await recompressHtml(outputDir, html)

  if (backend === 'github-pages') {
    await writeGitHubPagesFiles(outputDir)
  } else if (backend === 'cloudflare-pages') {
    await writeCloudflareFiles(outputDir)
  }
}

async function recompressHtml(outputDir: string, html: string): Promise<void> {
  const buf = Buffer.from(html)
  const gz = Bun.gzipSync(buf)
  const br = brotliCompressSync(buf)

  await Promise.all([
    Bun.write(join(outputDir, 'index.html.gz'), gz),
    Bun.write(join(outputDir, 'index.html.br'), br),
    Bun.write(join(outputDir, '404.html.gz'), gz),
    Bun.write(join(outputDir, '404.html.br'), br),
  ])
}

async function writeGitHubPagesFiles(outputDir: string): Promise<void> {
  await Bun.write(join(outputDir, '.nojekyll'), '')
}

async function writeCloudflareFiles(outputDir: string): Promise<void> {
  await Bun.write(join(outputDir, '_redirects'), '/* /index.html 200\n')

  await Bun.write(
    join(outputDir, '_headers'),
    [
      '/api-data/*',
      '  Cache-Control: public, max-age=31536000, immutable',
      '  Access-Control-Allow-Origin: *',
      '',
      '/uploads/*',
      '  Cache-Control: public, max-age=31536000, immutable',
      '',
      '/_app/*',
      '  Cache-Control: public, max-age=31536000, immutable',
      '',
    ].join('\n')
  )

  await Bun.write(
    join(outputDir, 'wrangler.toml'),
    [
      '# Generated by rctf export',
      '# Customize the name and other settings as needed',
      'name = "rctf-archive"',
      'compatibility_date = "2025-01-01"',
      'pages_build_output_dir = "."',
      '',
    ].join('\n')
  )
}
