name: Tests

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

concurrency:
  group: tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-bun-deps
      - run: bun run lint
      - run: bun run format:check

  typecheck:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-bun-deps
      - run: bun run typecheck

  test-server:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-bun-deps
        with:
          install-args: --filter @rctf/api --filter @rctf/cli --filter server-tests
      - run: bun run test:server

  test-admin-bot:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-bun-deps
        with:
          install-args: --filter @rctf/admin-bot --filter admin-bot-tests
      - run: bun run test:admin-bot

  test-admin-bot-e2e:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-bun-deps
        with:
          install-args: --filter @rctf/admin-bot --filter admin-bot-e2e-tests
      - run: bun run test:admin-bot:e2e
